# Generated by Django 4.2 on 2023-10-11 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='activite', verbose_name="Image de l'activité"),
        ),
        migrations.AlterField(
            model_name='depense',
            name='eleve',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.eleve', verbose_name='Personne concernée'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='recu',
            field=models.ImageField(blank=True, null=True, upload_to='recu', verbose_name='Réçu de paiement'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='profil',
            field=models.ImageField(blank=True, null=True, upload_to='profils', verbose_name='Photo de profil'),
        ),
    ]
